const translations_es = {
    'document_title': 'Análisis de Sistemas de Primer y Segundo Orden',
    'title_main': '⚙️ Respuesta Temporal de Sistemas de Primer y Segundo Orden',
    'config_title': 'Configuración de la Simulación',
    'loop_type_label': 'Tipo de Lazo:',
    'loop_open': 'Lazo Abierto',
    'loop_closed': 'Lazo Cerrado (Controlador PID)',
    'input_type_label': 'Tipo de Entrada $R(s)$: ',
    'input_step': 'Escalón (Step)',
    'input_ramp': 'Rampa',
    'input_sin': 'Senoidal (Seno)',
    'input_params_title': 'Parámetros de la Entrada',
    'step_min_label': 'Valor Mínimo $R_{\\min}$ [-100, 100]:',
    'step_max_label': 'Valor Máximo $R_{\\max}$ [-100, 100]:',
    'ramp_slope_label': 'Pendiente ($m$) [0.1, 10]:',
    'sin_amp_label': 'Amplitud ($A$) [0.1, 10]:',
    'sin_freq_label': 'Frecuencia Angular ($\\omega$) [0.1, 10]:',
    'controller_title': 'Controlador **PID** ($G_c(s)$)',
    'kc_label': 'Ganancia Control ($K_c$) [0.1, 100]:',
    'ti_label': 'Tiempo Integral ($T_i$) [0.001, $\\approx \\infty$]:',
    'tdc_label': 'Tiempo Derivativo ($T_{d,c}$) [0.0, 100]:',
    'system_params_title': 'Parámetros del Sistema ($G_p(s)$)',
    'system_order_label': 'Orden del Sistema:',
    'order_first': 'Primer Orden (FO)',
    'order_second': 'Segundo Orden (SO)',
    'kp_label': 'Ganancia ($K_p$) [0.1, 10]:',
    'tau_label': 'Constante de Tiempo ($\\tau$) [0.1, 100]:',
    'wn_label': 'Frecuencia Natural ($\\omega_n$) [0.1, 10]:',
    'zeta_label': 'Factor de Amort. ($\\zeta$) [-5, 5]:',
    'td_label': 'Tiempo Muerto Físico ($T_d$) [0.0, 20]:',
    'ft_diagram_title': 'Función de Transferencia y Diagrama',
    'button_simulate': '➕ Simular y Añadir Línea',
    'button_clear_responses': '🗑️ Borrar Salidas Y(t)',
    'button_clear_all': '🗑️ Borrar Todo',
    'button_download_image': '🖼️ Descargar Gráfica (PNG)',
    'button_download_data': '📊 Descargar Datos (CSV)',
    'chart_title': 'Respuesta Temporal del Sistema $Y(t)$',
    
    // CRÉDITO ACTUALIZADO
    'credit': 'Hecho por Julián Hernández y Gemini (Simulación basada en Euler Forward) Última actualización: 28/11/2025',
    
    // Textos dinámicos y de la gráfica
    'label_open_loop_abbr': 'L.A.', 
    'label_closed_loop_abbr': 'L.C.', 
    'label_first_order_abbr': 'FO',
    'label_second_order_abbr': 'SO',
    'input_label_r': 'Entrada R(t)',
    'input_abbr_step': 'E', 
    'input_abbr_ramp': 'R', 
    'input_abbr_sin': 'S', 
    'tooltip_time': 'Tiempo: ',
    'chart_y_axis': 'Amplitud (R(t) / Y(t))',
    'chart_x_axis': 'Tiempo (s)',
    'chart_empty_text': 'Pulse "Simular y Añadir Línea" para ver la respuesta temporal',
    'chart_title_sim_prefix': 'Respuesta de Sistemas de ',
    'chart_title_sim_suffix': ' Simulaciones',
    'diagram_title_open': 'Diagrama de Bloques (Lazo Abierto)',
    'diagram_title_closed': 'Diagrama de Bloques (Lazo Cerrado - Controlador PID)',
    
    // CLAVES PARA DIAGRAMA
    'diagram_delay_block': 'Retardo Td',
    'diagram_feedback_block': 'H(s)=1'
};